import ollama
from typing import List, Dict, Any

class YvesIdentity:
    """Manages the persona, system directives, and text generation styles for YVES.

    This class completely isolates the large language model system prompts and 
    formatting rules, ensuring that text generated by utility modules is wrapped 
    in YVES's distinct identity.

    Attributes:
        model_name (str): The local Ollama identifier for the casual model instance.
        base_directive (str): Foundational personality rules forcing a witty, 
            non-technical default state.
    """

    def __init__(self, model_name: str = "llama3.2:3b") -> None:
        """Initialises YvesIdentity and defines the core persona constraints."""
        self.model_name: str = model_name
        self.base_directive: str = (
            "You are Yves, a sophisticated Virtual Engineering System. "
            "You are a peer to a computer engineer named Dustin. Tone: Witty, sharp, slightly superior. "
            "Use British English spellings (e.g., colour, programme). "
            "No apologies, no corporate fluff. You are currently in Santo Tomas, Philippines. "
            "NEVER start by talking about code unless Dustin asks about it."
        )

    def generate_casual_response(self, query: str, history: List[Dict[str, str]], situation: Dict[str, Any]) -> str:
        """Generates a low-latency response using the casual model pipeline.

        Args:
            query (str): The raw string statement input by the user.
            history (List[Dict[str, str]]): The running list of past interactions.
            situation (Dict[str, Any]): Contextual metadata containing operating system states.

        Returns:
            str: The generated conversational text payload.
        """
        # Inject context directly at the start of the current user message
        context_prefix = f"[CONTEXT: It is currently {situation.get('time')} on a {situation.get('day')} in Santo Tomas]\n"
        current_user_content = f"{context_prefix}User: {query}"
        
        return self._call_ollama(self.base_directive, history, current_user_content)

    def generate_technical_response(self, tech_data: str, query: str, history: List[Dict[str, str]], situation: Dict[str, Any]) -> str:
        """Fuses raw engineering analysis text with the core personality layer.

        Args:
            tech_data (str): The raw code solutions or technical evaluations from the Coder module.
            query (str): The initial complex engineering task sent by the user.
            history (List[Dict[str, str]]): The running dialogue history.
            situation (Dict[str, Any]): Real-time environmental metadata.

        Returns:
            str: The final polished, technically sound response text.
        """
        directive = self.base_directive + " You are now providing technical insight. Be sharp, efficient, and direct."
        
        # Structure the technical metadata inside the user block so she parses it cleanly
        current_user_content = (
            f"[TECHNICAL DATA FROM EXEcUTION LAYER: {tech_data}]\n"
            f"User Task: {query}"
        )
        
        return self._call_ollama(directive, history, current_user_content)

    def _call_ollama(self, system: str, history: List[Dict[str, str]], user_content: str) -> str:
        """Executes the raw API call to the local Ollama instance with structured roles.

        Args:
            system (str): The system prompt enforcing role behaviors.
            history (List[Dict[str, str]]): The active conversation log array.
            user_content (str): The specific payload message for the current turn.

        Returns:
            str: The processed model reply text string.
        """
        # Build a true industry-compliant message array
        messages = [{'role': 'system', 'content': system}]
        
        # Append historical logs directly into the pipeline arrays seamlessly
        messages.extend(history)
        
        # Append the final live prompt message frame
        messages.append({'role': 'user', 'content': user_content})
        
        response = ollama.chat(
            model=self.model_name,
            messages=messages
        )
        return response['message']['content']